"""Fabrication de features versionnées et strictement temporelles."""

from metiquo.features.form import (
    FormWindow,
    RecentFormCalculator,
    RecentFormFeatureResult,
    RecentFormParameters,
    TeamRecentForm,
    recent_form_feature_definitions,
)
from metiquo.features.rating import (
    EloParameters,
    EloRatingCalculator,
    RatingFeatureResult,
    RatingTransition,
    TeamRating,
    rating_feature_definitions,
)
from metiquo.features.registry import (
    FeatureDefinitionSpec,
    FeatureRegistry,
    FeatureRegistryConflictError,
    FeatureSetSpec,
    RegisteredFeatureDefinition,
    RegisteredFeatureSet,
    RegisteredFeatureVector,
    UnregisteredFeatureError,
)
from metiquo.features.side import (
    SideFeatureCalculator,
    SideFeatureResult,
    SideParameters,
    SideSample,
    TargetSide,
    TargetSideScenario,
    TeamSideStrength,
    side_feature_definitions,
)
from metiquo.features.temporal import (
    AsOfGameBatch,
    AsOfGameRepository,
    AsOfInputAudit,
    CutoffViolationError,
    FeatureCutoff,
    HistoricalGame,
    HistoricalTeamGame,
    latest_entity_revisions_as_of,
    polars_strictly_before,
    strictly_before_cutoff,
)

__all__ = [
    "AsOfGameBatch",
    "AsOfGameRepository",
    "AsOfInputAudit",
    "CutoffViolationError",
    "EloParameters",
    "EloRatingCalculator",
    "FeatureCutoff",
    "FeatureDefinitionSpec",
    "FeatureRegistry",
    "FeatureRegistryConflictError",
    "FeatureSetSpec",
    "FormWindow",
    "HistoricalGame",
    "HistoricalTeamGame",
    "RatingFeatureResult",
    "RatingTransition",
    "RecentFormCalculator",
    "RecentFormFeatureResult",
    "RecentFormParameters",
    "RegisteredFeatureDefinition",
    "RegisteredFeatureSet",
    "RegisteredFeatureVector",
    "SideFeatureCalculator",
    "SideFeatureResult",
    "SideParameters",
    "SideSample",
    "TargetSide",
    "TargetSideScenario",
    "TeamRating",
    "TeamRecentForm",
    "TeamSideStrength",
    "UnregisteredFeatureError",
    "latest_entity_revisions_as_of",
    "polars_strictly_before",
    "rating_feature_definitions",
    "recent_form_feature_definitions",
    "side_feature_definitions",
    "strictly_before_cutoff",
]
