"""prematch bookmaker market history

Revision ID: 0013
Revises: 0012
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookmaker_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bookmaker", sa.String(), nullable=False),
        sa.Column("game", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column("competition_key", sa.String(), nullable=False),
        sa.Column("competition_name", sa.String(), nullable=True),
        sa.Column("category_name", sa.String(), nullable=True),
        sa.Column("participants", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("participant_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stop_reason", sa.String(), nullable=True),
        sa.Column("metadata_raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("bookmaker = 'stake'"),
        sa.CheckConstraint("status IN ('scheduled', 'live', 'closed', 'unknown')"),
        sa.CheckConstraint("(stopped_at IS NULL) = (stop_reason IS NULL)"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bookmaker", "game", "source_id"),
    )
    op.create_index(
        "ix_bookmaker_events_matching",
        "bookmaker_events",
        ["game", "starts_at", "competition_key"],
        unique=False,
    )
    op.create_index(
        "ix_bookmaker_events_participants",
        "bookmaker_events",
        ["participant_keys"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "bookmaker_payloads",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("sha256"),
    )
    op.create_table(
        "bookmaker_markets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("identity_key", sa.String(length=64), nullable=False),
        sa.Column("identity_basis", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("family", sa.String(), nullable=True),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("period", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["bookmaker_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "identity_key"),
    )
    op.create_table(
        "bookmaker_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capture_times", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("started_at <= finished_at AND finished_at < scheduled_start_at"),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["bookmaker_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payload_sha256"],
            ["bookmaker_payloads.sha256"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "event_id"),
    )
    op.create_index(
        "ix_bookmaker_snapshots_event_time",
        "bookmaker_snapshots",
        ["event_id", "finished_at"],
        unique=False,
    )
    op.create_table(
        "bookmaker_selections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("market_id", sa.Uuid(), nullable=False),
        sa.Column("identity_key", sa.String(length=64), nullable=False),
        sa.Column("identity_basis", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("accessible_label", sa.String(), nullable=True),
        sa.Column("column_label", sa.String(), nullable=True),
        sa.Column("line", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("line_raw", sa.String(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ordinal IS NULL OR ordinal > 0"),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["bookmaker_markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id", "identity_key"),
    )
    op.create_table(
        "bookmaker_match_links",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["bookmaker_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_bookmaker_match_links_match_id"),
        "bookmaker_match_links",
        ["match_id"],
        unique=False,
    )
    op.create_table(
        "bookmaker_quotes",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("selection_id", sa.Uuid(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tab", sa.String(), nullable=False),
        sa.Column("odds", sa.Numeric(precision=24, scale=12), nullable=True),
        sa.Column("odds_raw", sa.String(), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.CheckConstraint("odds IS NULL OR (odds > 1 AND odds < 1000000000)"),
        sa.ForeignKeyConstraint(
            ["selection_id"],
            ["bookmaker_selections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["bookmaker_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "selection_id", "observed_at"),
    )
    op.create_index(
        "ix_bookmaker_quotes_selection_time",
        "bookmaker_quotes",
        ["selection_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_bookmaker_quotes_time",
        "bookmaker_quotes",
        ["observed_at"],
        unique=False,
        postgresql_using="brin",
    )
    op.execute("""INSERT INTO script_schedules
      (id, cron, timezone, enabled, next_run_at, revision)
      VALUES ('stake-markets', '*/10 * * * *', 'Europe/Paris', true,
        to_timestamp((floor(extract(epoch from now()) / 600) + 1) * 600), 1)
      ON CONFLICT (id) DO NOTHING""")
    op.execute("""CREATE FUNCTION bookmaker_guard_quote() RETURNS trigger
      LANGUAGE plpgsql AS $$
      DECLARE e uuid; started timestamptz; ended timestamptz;
              scheduled timestamptz; selection_event uuid;
      BEGIN
        SELECT event_id, started_at, finished_at, scheduled_start_at
          INTO e, started, ended, scheduled FROM bookmaker_snapshots WHERE id=NEW.snapshot_id;
        SELECT m.event_id INTO selection_event FROM bookmaker_selections s
          JOIN bookmaker_markets m ON m.id=s.market_id WHERE s.id=NEW.selection_id;
        IF e IS DISTINCT FROM selection_event OR NEW.observed_at < started
          OR NEW.observed_at > ended OR NEW.observed_at >= scheduled THEN
          RAISE EXCEPTION 'Invalid pre-match quote provenance';
        END IF;
        RETURN NEW;
      END $$""")
    op.execute("""CREATE TRIGGER bookmaker_quote_provenance BEFORE INSERT ON bookmaker_quotes
      FOR EACH ROW EXECUTE FUNCTION bookmaker_guard_quote()""")
    op.execute("""CREATE FUNCTION bookmaker_guard_snapshot() RETURNS trigger
      LANGUAGE plpgsql AS $$ BEGIN
        IF NEW.scheduled_start_at <= clock_timestamp() OR EXISTS (
          SELECT 1 FROM bookmaker_events WHERE id=NEW.event_id AND stopped_at IS NOT NULL
        ) THEN RAISE EXCEPTION 'Event no longer eligible for pre-match collection'; END IF;
        RETURN NEW;
      END $$""")
    op.execute("""CREATE TRIGGER bookmaker_snapshot_prematch BEFORE INSERT ON bookmaker_snapshots
      FOR EACH ROW EXECUTE FUNCTION bookmaker_guard_snapshot()""")
    op.execute("""CREATE FUNCTION bookmaker_keep_stop() RETURNS trigger
      LANGUAGE plpgsql AS $$ BEGIN
        IF OLD.stopped_at IS NOT NULL AND
          (OLD.stopped_at IS DISTINCT FROM NEW.stopped_at OR
           OLD.stop_reason IS DISTINCT FROM NEW.stop_reason) THEN
          RAISE EXCEPTION 'A stopped bookmaker event cannot resume collection';
        END IF;
        RETURN NEW;
      END $$""")
    op.execute("""CREATE TRIGGER bookmaker_event_stop BEFORE UPDATE ON bookmaker_events
      FOR EACH ROW EXECUTE FUNCTION bookmaker_keep_stop()""")
    op.execute("""CREATE VIEW bookmaker_current_quotes AS
      WITH latest AS (
        SELECT DISTINCT ON (event_id) id, event_id, finished_at
        FROM bookmaker_snapshots ORDER BY event_id, finished_at DESC, id
      )
      SELECT DISTINCT ON (q.selection_id)
        e.id AS event_id, e.bookmaker, e.game, e.source_id AS event_source_id,
        e.source_url, e.competition_key, e.competition_name, e.participants, e.starts_at,
        e.stopped_at, e.stop_reason, m.id AS market_id, m.label AS market_label,
        m.family, m.scope, m.period, s.id AS selection_id, s.label AS selection_label,
        s.accessible_label, s.column_label, s.line, s.line_raw, s.ordinal,
        q.odds, q.odds_raw, q.disabled, q.observed_at, q.snapshot_id,
        (e.stopped_at IS NULL AND e.starts_at > now()) AS collecting_prematch
      FROM latest l JOIN bookmaker_events e ON e.id=l.event_id
      JOIN bookmaker_quotes q ON q.snapshot_id=l.id
      JOIN bookmaker_selections s ON s.id=q.selection_id
      JOIN bookmaker_markets m ON m.id=s.market_id
      ORDER BY q.selection_id, q.observed_at DESC""")
    op.execute("""DO $$ BEGIN
      IF EXISTS (SELECT FROM pg_roles WHERE rolname='metiquo_api') THEN
        GRANT SELECT ON bookmaker_events, bookmaker_payloads, bookmaker_snapshots,
          bookmaker_markets, bookmaker_selections, bookmaker_quotes, bookmaker_match_links,
          bookmaker_current_quotes TO metiquo_api;
      END IF;
      IF EXISTS (SELECT FROM pg_roles WHERE rolname='metiquo_worker') THEN
        GRANT SELECT, INSERT, UPDATE ON bookmaker_events, bookmaker_markets,
          bookmaker_selections, bookmaker_match_links TO metiquo_worker;
        GRANT SELECT, INSERT ON bookmaker_payloads, bookmaker_snapshots, bookmaker_quotes
          TO metiquo_worker;
        GRANT SELECT ON bookmaker_current_quotes TO metiquo_worker;
        REVOKE DELETE ON bookmaker_events, bookmaker_markets, bookmaker_selections,
          bookmaker_match_links FROM metiquo_worker;
        REVOKE UPDATE, DELETE ON bookmaker_payloads, bookmaker_snapshots, bookmaker_quotes
          FROM metiquo_worker;
      END IF;
    END $$""")


def downgrade() -> None:
    op.execute("UPDATE script_schedules SET enabled=false WHERE id='stake-markets'")
    op.execute("DROP VIEW bookmaker_current_quotes")
    op.execute("DROP TRIGGER bookmaker_quote_provenance ON bookmaker_quotes")
    op.execute("DROP TRIGGER bookmaker_snapshot_prematch ON bookmaker_snapshots")
    op.execute("DROP TRIGGER bookmaker_event_stop ON bookmaker_events")
    op.execute("DROP FUNCTION bookmaker_guard_quote()")
    op.execute("DROP FUNCTION bookmaker_guard_snapshot()")
    op.execute("DROP FUNCTION bookmaker_keep_stop()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_bookmaker_quotes_time", table_name="bookmaker_quotes", postgresql_using="brin"
    )
    op.drop_index("ix_bookmaker_quotes_selection_time", table_name="bookmaker_quotes")
    op.drop_table("bookmaker_quotes")
    op.drop_index(op.f("ix_bookmaker_match_links_match_id"), table_name="bookmaker_match_links")
    op.drop_table("bookmaker_match_links")
    op.drop_table("bookmaker_selections")
    op.drop_index("ix_bookmaker_snapshots_event_time", table_name="bookmaker_snapshots")
    op.drop_table("bookmaker_snapshots")
    op.drop_table("bookmaker_markets")
    op.drop_table("bookmaker_payloads")
    op.drop_index(
        "ix_bookmaker_events_participants", table_name="bookmaker_events", postgresql_using="gin"
    )
    op.drop_index("ix_bookmaker_events_matching", table_name="bookmaker_events")
    op.drop_table("bookmaker_events")
    # ### end Alembic commands ###
